# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad3d726b4a77bbbcb8ac651ad335170b1d85b2fe4a449e6e1e58143fc1f0d03dd9d2e0be41dbdd8cd3000d00d71483b92a288a88364d7626f708da449c4c46df

test:
  secret_key_base: 4fe21cab1840e63d4e091dbc5775b5889f4f423a35596cb46cb8c8504319b37e152fe2c2f177800ec19232bea5858464a698107f774cc7a9648149356064fec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
