# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e8ab89b489520dc5a8fbe7c679e1db63716b6381799536d1ec89e97ac8efbd81cd68f2bf8126df22cc2f4b7911223de10421de54b6dfc145fe9033274337f9

test:
  secret_key_base: e2597462376d757f3a73fab89940e0d89bb745e054f7a4e1697c5098b7a1d470008c0ac724172f19c4750ab193b87fd6a0886db035f4661aa0e8b274df2fbd95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
